version: '3.4'

services:
  stone.psp.web.api:
    image: ${DOCKER_REGISTRY-}stonepspwebapi
    build:
      context: .
      dockerfile: Stone.PSP.Web.API/Dockerfile
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: "Psp@2023@ps"
    volumes:
        - c:\dados\volumes\mssql:/var/opt/mssql3  
    ports:
        - '1433:1433'    
    expose:
        - 1433
